# Generated by Django 3.2.9 on 2021-11-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211122_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='topcategory',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
    ]
