# Generated by Django 3.2.9 on 2021-11-24 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_topcategory_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topcategory',
            options={'verbose_name': 'Top category', 'verbose_name_plural': 'Top categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.category'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('has_discount', models.BooleanField(default=False)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image', models.ImageField(upload_to='products/')),
                ('sold', models.IntegerField(default=0)),
                ('status', models.SmallIntegerField(choices=[(0, 'New'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.category')),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-sold'], name='main_produc_sold_2005f7_idx'),
        ),
    ]
