# Generated by Django 3.2.9 on 2021-11-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211124_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='main_produc_sold_2005f7_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', '-sold'], name='main_produc_status_a0101a_idx'),
        ),
    ]
