# Generated by Django 3.2.9 on 2021-11-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_available'),
        ('cart', '0002_alter_order_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProductModel',
            new_name='OrderProduct',
        ),
    ]
