# Generated by Django 3.2.9 on 2021-11-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_orderproductmodel_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
